### ISSUE TITLE
A 'br tag above a input element that I am trying to set prevents it from being set

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#108] opened 2017-05-02 06:52 UTC
Well the solution is to avoid using 'br tags.

I have an input field and I try to set its value and somewhere above in the html was a 'br tag, the value would not get set. Removal of the 'br tag allowed it to be set.

Not an important bug for me anymore, just avoid 'br.

**Comment by fomkin** [comment] 2017-07-01 16:25
Need to test it in 0.4.0 release.

**Comment by Tvaroh** [comment] 2017-07-04 10:28
@fomkin still the case in 0.4.0.

One observation: when I add *br* tag and do not refresh the page (just wait for Korolev to update the DOM asynchronously), then it keeps working. But after page reload it breaks.

Also, even though I add a single *br* tag, there are actually two in the DOM.

Code to reproduce:

```scala
import korolev._
import korolev.blazeServer._
import korolev.execution._
import korolev.server._

import scala.concurrent.Future

object BrFailureExample extends KorolevBlazeServer {

  val applicationContext = ApplicationContext[Future, Boolean, Any]

  import applicationContext._
  import symbolDsl._

  val inputId = elementId

  val service = blazeService[Future, Boolean, Any] from KorolevServiceConfig[Future, Boolean, Any](
    stateStorage = StateStorage.default(false),
    serverRouter = ServerRouter.empty[Future, Boolean],
    render = {
      case _ =>
        'body(
          'div("Br failure example"),
          'div(
            'br(),
            'input(
              inputId,
              'type /= "text"
            )
          ),
          'div(
            'button(
              eventWithAccess('click) { access =>
                deferredTransition {
                  access.property(inputId).set('value, "ololo").map(_ => emptyTransition)
                }
              },
              "Click"
            )
          )
        )
    }
  )
}
```

**Comment by fomkin** [comment] 2017-07-04 13:37
Looks like it cause of bug in text rendering. `AbstractTextRenderContext` (and old `VDom.toString`) renders `br` as `<br></br>`. It is not follow HTML standard.

**Comment by Tvaroh** [comment] 2017-07-04 13:41
Good hypothesis. If so, then it affects all HTML tags that are self-closing, here is the [list](https://stackoverflow.com/a/8853550/312708).

**Comment by Tvaroh** [comment] 2017-07-04 13:46
@fomkin just checked, it does work fine with *img*, *area*, *hr*. And they are not duplicated in the DOM. Seems *br* is kind of special.

**Comment by fomkin** [comment] 2017-07-06 14:40
See to ways to fix it (in Levsha Project):
1. Prohibit `'br` in compile time.
2. Text tags in `AbstractTextRenderContext.closeNode` in runtime.

**Comment by fomkin** [comment] 2019-10-22 14:42
In new Levsha DSL `br` tag is marked deprecated.

**Closed by fomkin** 2019-10-22 14:42 UTC
Labels: bug
